baseURL = "https://example.com"
languageCode = "en-us"
title = "Archie"
theme="archie"
copyright = "© Amrit"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="dark"
	useCDN=false
	subtitle = "Machine Learning Blogs and more"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/AmritRVardhan"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/amrit-raj-vardhan/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Heatmap"
url = "/heatmap"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5
